@startuml
skinparam shadowing false

actor Administrator order 1
database "Configuration\nstorage" order 2
participant "Configuration\nservice" order 3
participant "Subscribers\n(producers, consumers)" order 4


"Configuration\nservice" ->> "Configuration\nstorage": listen
Administrator -> "Configuration\nstorage": new configuration
activate Administrator
"Configuration\nstorage" --> Administrator: confirmation
deactivate Administrator
"Configuration\nstorage" --> "Configuration\nservice": new configuration
activate "Configuration\nservice"
"Configuration\nservice" ->> "Subscribers\n(producers, consumers)": new configuration
"Configuration\nservice" ->> "Configuration\nstorage": listen
deactivate "Configuration\nservice"
|||

@enduml