@startuml

skinparam shadowing false

interface Map
interface Cache

interface ConsumerService
interface Producer

Map <|--right- Cache
Cache <|.. KafkaCache


KafkaCache *--left- ConsumerService
KafkaCache *--right- Producer

@enduml